fix: build fails with spi driver error
**Whats the current behavior**

When building the application in embedded mode, the build fails with
spi driver errors:

```diff
- In file included from components/hagl_hal/src/hagl_hal_single.c:53:
- components/hagl_hal/include/mipi_display.h:46:10: fatal error: driver/spi_master.h: No such file or directory
-    46 | #include <driver/spi_master.h>
-       |          ^~~~~~~~~~~~~~~~~~~~~
- compilation terminated.
- In file included from components/hagl_hal/src/hagl_hal_double.c:52:
- components/hagl_hal/include/mipi_display.h:46:10: fatal error: driver/spi_master.h: No such file or directory
-    46 | #include <driver/spi_master.h>
-       |          ^~~~~~~~~~~~~~~~~~~~~
- compilation terminated.
- components/hagl_hal/src/mipi_display.c:46:10: fatal error: driver/spi_master.h: No such file or directory
-    46 | #include <driver/spi_master.h>
-       |          ^~~~~~~~~~~~~~~~~~~~~
```

This is caused by an automatic upgrade to an esp-idf version with breaking changes (v6+).

**What is the new behavior**

Until our code has run through the migration steps (discussed in [#151]), we are locked
in to version 4.4.x. This commit sets the esp-idf version to the latest stable version
v4.4.0.

closes [#148]

[#151]: https://gitlab.com/ohsnaparts/osasoftworks/zube/presence-cube/-/issues/151
[#148]: https://gitlab.com/ohsnaparts/osasoftworks/zube/presence-cube/-/issues/148