fix: broken ci-pipeline
Presently builds are failing due to missing dependency / incompatible
depenencies.

https://gitlab.com/ohsnaparts/osasoftworks/zube/presence-cube/-/jobs/6517337481

```
********************************************************************************
Processing native-dev (platform: native)
--------------------------------------------------------------------------------
Platform Manager: Installing native
Downloading...
Unpacking...
Platform Manager: native@1.2.1 has been installed!
Tool Manager: Installing toolchain-riscv32-esp @ *
Tool Manager: Warning! More than one package has been found by toolchain-riscv32-esp @ * requirements:
Tool Manager:  - espressif/toolchain-riscv32-esp@12.2.0+20230208
Tool Manager:  - platformio/toolchain-riscv32-esp@13.2.0+20230928
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (shown above) to avoid name conflicts
Downloading...
Unpacking...
Tool Manager: toolchain-riscv32-esp@12.2.0+20230208 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40300.0
Error: Could not find the package with 'platformio/tool-scons @ ~4.40300.0' requirements for your system 'linux_x86_64'
Build-PioEnvironment: /builds/ohsnaparts/osasoftworks/zube/presence-cube/build_env.ps1:13
Line |
  13 |  Build-PioEnvironment -Environments $Environments
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | An error occured while building the native-dev environment.
Build-PioEnvironment: /builds/ohsnaparts/osasoftworks/zube/presence-cube/build_env.ps1:13
Line |
```

- upgrading platformio to latest minor version
- removes sdkconfig.local reference from config.h as it isn't available in CI
- adds iface coding guideline and refactors logger to follow it
- updates powershell version to 7.2 for CI
- inlines math_util library into presence-cube.domain
- replaces CI incompatibe -CommandWithArgs with -Command for Invoke-ScriptTests